### ISSUE TITLE
Please mention more clearly that pgloader is not available for Windows

### ISSUE THREAD

**Issue by ReinierNL** [dimitri/pgloader#1017]
I was looking at [https://pgloader.readthedocs.io/en/latest/index.html](https://pgloader.readthedocs.io/en/latest/index.html)
and at [https://pgloader.readthedocs.io/en/latest/ref/dbf.html](https://pgloader.readthedocs.io/en/latest/ref/dbf.html)
and thought I should start using pgloader.
It took me quite a while (I also looked here: [https://github.com/dimitri/pgloader/releases](https://github.com/dimitri/pgloader/releases) )
before I found that there actually is no Windows version.

Could you please mention that here and there more prominently?

**Comment by richdevboston** [comment]
This needs to be stated right up front!!   You are wasting people's time by making them compile from C or Common LISP source code (unless the person was a pure CS major in college and had the discrete pleasure of taking Common LISP courses).

This cry for help is still unanswered after more than 2 years.  
[https://github.com/dimitri/pgloader/issues/652](url)

Unbelievable !!! So much effort just to get something to compile and run on Windows.  POSIX was supposed to solve these kind of problems.  Apparently POSIX is a failure?  

This supposed "answer" post opened up with a response to the initial BUG report by a programmer who NEVER used windows?  Have you been buried in a unix rathole for 40 years?  "I don't know windows for not having used it ever, but I could see about building a pgloader.exe with some sponsoring for the time it will take. See about buying a pgloader Moral License at http://pgloader.io/pgloader-moral-license.html (the « Custom Development » one, or if other windows users also chime in a bunch of Partner level ones) so that I can see about that. Thanks."   
The entire answer stream seems like job security for UNIX guys, starting by asking for funding to make a single instance binary executable for Windows for ONE application, pgloader.exe.   

Common LISP seems to be part of the PostgreSQL community mistake.  Python 3 would be better for building pgloader.exe because it is cross-platform and more non-computer scientists understand it well.  

How about getting an open source Windows programmer to give it a try with a Python version of the source code??  

Off Soap box!

**Comment by vrtareg** [comment]
I was able to successfully build pgloader on Windows 10 WSL Ubuntu shell and run it.

As per https://github.com/dimitri/pgloader install additional packages

```
apt install install sbcl unzip libsqlite3-dev make curl gawk freetds-dev libzip-dev
apt install libsybdb5
apt install mysql-source-5.7
```

Ignore MSSQL error if you are not using MSSQL load.

Regards,
Areg

**Comment by bburns** [comment]
You can also just do

    sudo apt install pgloader

with the Ubuntu WSL

**Comment by kburchfiel** [comment]
I ended up installing it using the Windows Subsystem for Linux. Not the most direction option but it looks like it will work fine (although I may need to use it within Ubuntu--we'll see)
