### ISSUE TITLE
Not able to migrate MySQL database to PostgreSQL

### ISSUE THREAD

**Issue by XanderXaviour** [dimitri/pgloader#1073]
I am new to PostgreSQL and recently I was being asked to find out a way, how to migrate from MySQL database to PostgreSQL as my organization is considering shifting to PostgreSQL for some reasons. Now I came to know that pgloader is the best tool to do such activity so I tried to install and use. Now I am using this command to move a database 'Music' to PostgreSQL but getting some sort of error which I am not able to understand. Is there any way someone could guide me or help me how to migrate the database perfectly. 
Here is the command and error.
`pgloader mysql://root@localhost/Music pgsql://postgres@localhost/Music`
This is the output I am getting.

`2020-01-23T09:48:02.049000Z LOG Migrating from #<MYSQL-CONNECTION mysql://root@localhost:3306/Music {1005805E43}>`
`2020-01-23T09:48:02.052000Z LOG Migrating into #<PGSQL-CONNECTION pgsql://postgres@localhost:5432/Music {1005A55AB3}>`
`KABOOM!`
`INFO: Control stack guard page unprotected`
`Control stack guard page temporarily disabled: proceed with caution`

`What I am doing here?`

`Control stack exhausted (no more space for function call frames).`
`This is probably due to heavily nested or infinitely recursive function`
`calls, or a tail call that SBCL cannot or has not optimized away.`

`PROCEED WITH CAUTION.`

**Comment by XanderXaviour** [comment]
@dimitri I hope you can help.

**Comment by NeilMD** [comment]
I seem to encounter the same problem. I tried limiting the prefetch rows to 1000, batch size to 1MB, and batch rows to 100

`pgloader version 3.6.1
compiled with SBCL 1.4.16.debian
sb-impl::*default-external-format* :ANSI_X3.4-1968
tmpdir: #P"/tmp/pgloader/"
2020-01-24T01:54:15.012000Z NOTICE Starting pgloader, log system is ready.
2020-01-24T01:54:15.024000Z INFO Starting monitor
2020-01-24T01:54:15.027000Z LOG pgloader version "3.6.1"
2020-01-24T01:54:15.078000Z INFO Parsed command:
--
-- Main tables
--
load database
   from mssql://Kariire:Awsol12#@192.168.227.208/KariData
   into postgresql://postgres:Awsol12#@192.168.227.208/sakura
-- All below not required as present
with
   prefetch rows = 1000, batch size = 1MB, batch rows = 100
--cast
--   type bigint   when (= 20 precision)                   to bigint             drop typemod,
--   type int      when (= 11 precision)                   to integer            drop typemod,
--   type decimal  when (and (= 18 precision) (= 6 scale)) to "double precision" drop typemod,
--   type datetime2 to timestamptz
--   type datetime                                         to timestamp          drop default using zero-dates-to-null
--excluding table names matching ~/AO_/, ~/EVENTS/, ~/SECRETS/, ~/SNAPSHOTS/, ~/PLUGINDATA/, ~/scheduler_clustered_jobs/
-- we rename the dbo to public tables
alter schema 'dbo' rename to 'public'
--after load do
--$$ alter sequence journalentry_entry_id_seq rename to seq_journal_entry_id; $$
;

2020-01-24T01:54:16.358000Z DEBUG CONNECTED TO #<PGLOADER.PGSQL:PGSQL-CONNECTION pgsql://postgres@192.168.227.208:5432/sakura {1006924C53}>
2020-01-24T01:54:16.359000Z DEBUG SET client_encoding TO 'utf8'
2020-01-24T01:54:16.360000Z DEBUG SET application_name TO 'pgloader'
2020-01-24T01:54:16.400000Z LOG Migrating from #<MSSQL-CONNECTION mssql://Kariire@192.168.227.208:1433/KariData {10069238D3}>
2020-01-24T01:54:16.400000Z LOG Migrating into #<PGSQL-CONNECTION pgsql://postgres@192.168.227.208:5432/sakura {1006924C53}>
Max connections reached, increase value of TDS_MAX_CONN
2020-01-24T01:54:16.891000Z SQL MSSQL: sending query: -- params: dbname
--         table-type-name
--         including
--         filter-list-to-where-clause including
--         excluding
--         filter-list-to-where-clause excluding
  select c.TABLE_SCHEMA,
         c.TABLE_NAME,
         c.COLUMN_NAME,
         c.DATA_TYPE,
         CASE
         WHEN c.COLUMN_DEFAULT LIKE '((%' AND c.COLUMN_DEFAULT LIKE '%))' THEN
             CASE
                 WHEN SUBSTRING(c.COLUMN_DEFAULT,3,len(c.COLUMN_DEFAULT)-4) = 'newid()' THEN 'GENERATE_UUID'
                 WHEN SUBSTRING(c.COLUMN_DEFAULT,3,len(c.COLUMN_DEFAULT)-4) LIKE 'convert(%varchar%,getdate(),%)' THEN 'today'
                 WHEN SUBSTRING(c.COLUMN_DEFAULT,3,len(c.COLUMN_DEFAULT)-4) = 'getdate()' THEN 'CURRENT_TIMESTAMP'
                 WHEN SUBSTRING(c.COLUMN_DEFAULT,3,len(c.COLUMN_DEFAULT)-4) LIKE '''%''' THEN SUBSTRING(c.COLUMN_DEFAULT,4,len(c.COLUMN_DEFAULT)-6)
                 ELSE SUBSTRING(c.COLUMN_DEFAULT,3,len(c.COLUMN_DEFAULT)-4)
             END
         WHEN c.COLUMN_DEFAULT LIKE '(%' AND c.COLUMN_DEFAULT LIKE '%)' THEN
             CASE
                 WHEN SUBSTRING(c.COLUMN_DEFAULT,2,len(c.COLUMN_DEFAULT)-2) = 'newid()' THEN 'GENERATE_UUID'
                 WHEN SUBSTRING(c.COLUMN_DEFAULT,2,len(c.COLUMN_DEFAULT)-2) LIKE 'convert(%varchar%,getdate(),%)' THEN 'today'
                 WHEN SUBSTRING(c.COLUMN_DEFAULT,2,len(c.COLUMN_DEFAULT)-2) = 'getdate()' THEN 'CURRENT_TIMESTAMP'
                 WHEN SUBSTRING(c.COLUMN_DEFAULT,2,len(c.COLUMN_DEFAULT)-2) LIKE '''%''' THEN SUBSTRING(c.COLUMN_DEFAULT,3,len(c.COLUMN_DEFAULT)-4)
                 ELSE SUBSTRING(c.COLUMN_DEFAULT,2,len(c.COLUMN_DEFAULT)-2)
             END
         ELSE c.COLUMN_DEFAULT
         END,
         c.IS_NULLABLE,
         COLUMNPROPERTY(object_id(c.TABLE_NAME), c.COLUMN_NAME, 'IsIdentity'),
         c.CHARACTER_MAXIMUM_LENGTH,
         c.NUMERIC_PRECISION,
         c.NUMERIC_PRECISION_RADIX,
         c.NUMERIC_SCALE,
         c.DATETIME_PRECISION,
         c.CHARACTER_SET_NAME,
         c.COLLATION_NAME

    from INFORMATION_SCHEMA.COLUMNS c
         join INFORMATION_SCHEMA.TABLES t
              on c.TABLE_SCHEMA = t.TABLE_SCHEMA
             and c.TABLE_NAME = t.TABLE_NAME

   where     c.TABLE_CATALOG = 'KariData'
         and t.TABLE_TYPE = 'BASE TABLE'



order by c.table_schema, c.table_name, c.ordinal_position;
2020-01-24T01:54:19.137000Z SQL MSSQL: sending query: -- params: including
--         filter-list-to-where-clause including
--         excluding
--         filter-list-to-where-clause excluding
    select schema_name(schema_id) as SchemaName,
           o.name as TableName,
           REPLACE(i.name, '.', '_') as IndexName,
           co.[name] as ColumnName,
           i.is_unique,
           i.is_primary_key,
           i.filter_definition

    from sys.indexes i
         join sys.objects o on i.object_id = o.object_id
         join sys.index_columns ic on ic.object_id = i.object_id
             and ic.index_id = i.index_id
         join sys.columns co on co.object_id = i.object_id
             and co.column_id = ic.column_id

   where schema_name(schema_id) not in ('dto', 'sys')



order by SchemaName,
         o.[name],
         i.[name],
         ic.is_included_column,
         ic.key_ordinal;
2020-01-24T01:54:19.682000Z SQL MSSQL: sending query: -- params: dbname
--         including
--         filter-list-to-where-clause including
--         excluding
--         filter-list-to-where-clause excluding
   SELECT
           REPLACE(KCU1.CONSTRAINT_NAME, '.', '_') AS 'CONSTRAINT_NAME'
         , KCU1.TABLE_SCHEMA AS 'TABLE_SCHEMA'
         , KCU1.TABLE_NAME AS 'TABLE_NAME'
         , KCU1.COLUMN_NAME AS 'COLUMN_NAME'
         , KCU2.TABLE_SCHEMA AS 'UNIQUE_TABLE_SCHEMA'
         , KCU2.TABLE_NAME AS 'UNIQUE_TABLE_NAME'
         , KCU2.COLUMN_NAME AS 'UNIQUE_COLUMN_NAME'
         , RC.UPDATE_RULE AS 'UPDATE_RULE'
         , RC.DELETE_RULE AS 'DELETE_RULE'

    FROM INFORMATION_SCHEMA.REFERENTIAL_CONSTRAINTS RC
         JOIN INFORMATION_SCHEMA.KEY_COLUMN_USAGE KCU1
              ON KCU1.CONSTRAINT_CATALOG = RC.CONSTRAINT_CATALOG
                 AND KCU1.CONSTRAINT_SCHEMA = RC.CONSTRAINT_SCHEMA
                 AND KCU1.CONSTRAINT_NAME = RC.CONSTRAINT_NAME
         JOIN INFORMATION_SCHEMA.KEY_COLUMN_USAGE KCU2
              ON KCU2.CONSTRAINT_CATALOG = RC.UNIQUE_CONSTRAINT_CATALOG
                 AND KCU2.CONSTRAINT_SCHEMA = RC.UNIQUE_CONSTRAINT_SCHEMA
                 AND KCU2.CONSTRAINT_NAME = RC.UNIQUE_CONSTRAINT_NAME

   WHERE KCU1.ORDINAL_POSITION = KCU2.ORDINAL_POSITION
         AND KCU1.TABLE_CATALOG = 'KariData'
         AND KCU1.CONSTRAINT_CATALOG = 'KariData'
         AND KCU1.CONSTRAINT_SCHEMA NOT IN ('dto', 'sys')
         AND KCU1.TABLE_SCHEMA NOT IN ('dto', 'sys')
         AND KCU2.TABLE_SCHEMA NOT IN ('dto', 'sys')




ORDER BY KCU1.CONSTRAINT_NAME, KCU1.ORDINAL_POSITION;
2020-01-24T01:54:20.013000Z INFO Processing source catalogs
2020-01-24T01:54:20.124000Z NOTICE Prepare PostgreSQL database.
2020-01-24T01:54:21.429000Z DEBUG CONNECTED TO #<PGLOADER.PGSQL:PGSQL-CONNECTION pgsql://postgres@192.168.227.208:5432/sakura {1006924C53}>
2020-01-24T01:54:21.429000Z DEBUG SET client_encoding TO 'utf8'
2020-01-24T01:54:21.431000Z DEBUG SET application_name TO 'pgloader'
2020-01-24T01:54:21.442000Z DEBUG BEGIN
KABOOM!
INFO: Control stack guard page unprotected
Control stack guard page temporarily disabled: proceed with caution
2020-01-24T01:54:21.921000Z INFO Stopping monitor

What I am doing here?

Control stack exhausted (no more space for function call frames).
This is probably due to heavily nested or infinitely recursive function
calls, or a tail call that SBCL cannot or has not optimized away.

PROCEED WITH CAUTION.`

**Comment by XanderXaviour** [comment]
@NeilMD Any luck yet ?

**Comment by NeilMD** [comment]
> 
> 
> @NeilMD Any luck yet ?

None

**Comment by dimitri** [comment]
I remember having fixed a bug with similar symptoms, you could try building current HEAD and see if you still have the bug? Closing for cleaning purposes, please open again if you still need help here.

**Comment by danports** [comment]
I have the same problem with the latest Docker image. I didn't try any of the config tweaks @NeilMD did.

```
pgloader version "3.6.3~devel"
compiled with SBCL 1.4.16.debian
```

```
...
2020-05-31T06:56:36.394000Z DEBUG SET application_name TO 'pgloader'
2020-05-31T06:56:36.408000Z DEBUG BEGIN
KABOOM!
INFO: Control stack guard page unprotected
...
```

**Comment by dimitri** [comment]
The control stack (infinite recursion) problem is supposed to be solve in the following patch: https://github.com/dimitri/pgloader/commit/ab2cadff24f58c933b2c6afd29604c5e938eb8c7

Please share the result of `SELECT version()` from your target Postgres database.

**Comment by danports** [comment]
```
PostgreSQL 11.2-YB-2.1.6.0-b0 on x86_64-pc-linux-gnu, compiled by gcc (Homebrew gcc 5.5.0_4) 5.5.0, 64-bit
```
(YugabyteDB running the PostgreSQL front end)

**Comment by oliviernguyenquoc** [comment]
Same issue here.

Result of `SELECT version()`: PostgreSQL 12.1

**Comment by dimitri** [comment]
See #992 and https://github.com/dimitri/pgloader/commit/cc8975bb8837b8ec6957d51dad9bad75d31aa4f9
