### ISSUE TITLE
Port is ignored in MSSQL URI

### ISSUE THREAD

**Issue by itineric** [dimitri/pgloader#1094]
I'm launching pgloader with 2 URIs. My source URI has MSSQL type, it looks like: `mssql://user:pass@server:49242/database`

I get the following error:
`ERROR mssql: Failed to connect to mssql at "server" (port 49242) as user "user": %dbsqlexec fail`

I used tsql (freetds) to validate that my MSSQL info works fine. And it works.

Finally, I found the following line in the freetds (debug) log file after pgloader was executed:
`10:55:14.423698 6 (net.c:226):Connecting to 10.1.43.221 port 1433 (TDS version 7.4)`
The given IP is the one of the "server" from the MSSQL URI.

So I think that the port given in the MSSQL URI is ignored. As I dont know LISP, I dont know what to search for in the sources to fix it.

Can I get some help ?

**Comment by Harleqin** [comment]
Just looking at the source code, as far as I can see, you are correct that the port config is not used (`pgloader.source.mssql:open-connection`).  However it seems that the reason is that the option is not exposed by cl-mssql (`mssql:connect`), which seems to be the case because the C library doesn't expose it (`LOGINREC`), or at least not where the rest of the connection info goes in.

It _might_ be that this interface expects the port as part of the hostname, but I don't have the time and resources to test this out (or to debug C code).

Maybe you can try to work around the issue through port forwarding?

**Comment by gjvoosten** [comment]
@itineric I have the same problem (have multiple MS SQL Docker containers running on different ports), and indeed a DB URI like  `mssql://user:pass@server:49242/database` with the port number in it does not work. I've found that you can set the environment variable `TDSPORT` to the port number and that *does* work (see https://github.com/dimitri/pgloader/blob/master/src/parsers/command-mssql.lisp#L118-L119 ). E.g.
```env TDSPORT=49242 pgloader migrate.conf```

Note: I consider this merely a work-around; the port should simply be accepted as part of the URI and used in the connection.

@dimitri @phoe Would a fix be possible?

**Comment by itineric** [comment]
Another workaround is to fix the port using the freetds.conf file.

**Comment by dimitri** [comment]
As @phoe said the driver API we're using is lacking in how to pass down the port number. It's parsed correctly in the connection string by pgloader and then just ignored. Thanks to your report about the environment variable `TDSPORT` working, what we could do is set the value we parse in the connection string in the environment maybe?

I just pushed a patch that just does that. Please try it and report success/failure!

**Comment by gjvoosten** [comment]
Works like a charm, @dimitri ! :+1:
