### ISSUE TITLE
Date format support

### ISSUE THREAD

**Issue by ksiddi01** [dimitri/pgloader#1143]
I have a quick question.  Does pgloader supports 3 character month.
2018-JAN-01 12.23.35.230345

Thanks.

**Comment by dimitri** [comment]
Hi @ksiddi01 ; what happens when you try?

We are a small team with a shortage on time allocation, so that it would be best if you could try and make it work and get back with a concrete example in case you need help. The concrete example would preferably be shared in the form of a self-contained reproducible test case. Thanks!

Meanwhile I'm closing this issue, and please feel free to open it again if needed, of course.
