### ISSUE TITLE
3.6.2 Supported Postgresql Parameters | multiple readers per thread, rows per range = 50000

### ISSUE THREAD

**Issue by malceore** [dimitri/pgloader#1202]
I am unable to find a resolution to this issue, when I am migrating from Postgresql to Postgresql server am I not allowed to use the: "multiple readers per thread, rows per range = 50000"  in the with clause? I recently did a Mysql to Postgresql and adding these made our migration 5X faster. I get the below error for either command in any order when I try to use them in v3.6.2:

```
   WITH rows per range = 50000,
        ^ (Line 4, Column 6, Position 263)
In context PGSQL-OPTIONS:
While parsing PGSQL-OPTIONS. Expected:
```

Lastly I see in the readthedocs that rows per run is supported and this flag seems to indicate that multiple readers must be support, so I thought I would ask before I spend 19hrs next weekend trying to migrate this data.

**Comment by dimitri** [comment]
Hi @malceore ; those options are specific to MySQL. The reason it works faster is due to how MySQL usage of indexes to scan larger portion of tables work, and I don't believe you would have the same level of gains (if any at all) with Postgres. I would advice having more tables being done concurrently maybe, as a first step. Do you happen to have a giant table to copy over to the new database?

Finally, what's your use case with pgloader when moving from Postgres to Postgres?

**Comment by malceore** [comment]
Dang, well thanks for getting back to me. Due to complications during a software upgrade we now have to migrate data from one Postgresql server to the other. It is around 460GB and is mainly stored in just three very large tables. Right now I have compiled with a DYNSIZE of 22000 and "workers = 16, concurrency = 4, include drop, create no indexes;", but pgloader isn't using more than 5GB or 3 VCPU Cores and the migration is taking over nine hours to complete. I'd gladly try any recommendations though.

**Comment by dimitri** [comment]
If both the source and the target are using the same Postgres version, try pg_basebackup, or a Postgres streaming replication setup. Otherwise have a look at logical replication. Finally, if neither disk nor network bandwidth are your current bottleneck, we might try implementing the parallel / partial scan idea with Postgres... it might prove me wrong and make you happier.

**Comment by malceore** [comment]
I'll investigate those leads, thank you very much @dimitri!
