### ISSUE TITLE
readme - make it simpler for simple mysql import

### ISSUE THREAD

**Issue by wweevv-johndpope** [dimitri/pgloader#1413]
had to google around to find this - for majority of people having this on readme would be great.
https://datawookie.dev/blog/2021/03/resurrecting-a-mysql-database/

```
pgloader mysql://root:$MYSQL_ROOT_PASSWORD@172.17.0.2/backup \
         pgsql://postgres:$POSTGRES_PASSWORD@172.17.0.3/backup
```

**Comment by dimitri** [comment]
We have such docs coverage already:

  - https://pgloader.readthedocs.io/en/latest/quickstart.html#migrating-from-mysql
  - https://pgloader.readthedocs.io/en/latest/tutorial/tutorial.html#migrating-from-mysql-to-postgresql

I admit that then https://pgloader.readthedocs.io/en/latest/ref/mysql.html could do with a smoother intro.

**Comment by johndpope** [comment]
I went to that - it didn’t give me this exact nugget.
 consider people are writing (neat) blogs because the help / docs aren’t helpful or not clear concise. You’re better off having a link to those sites.
 
Don’t need to click through 6-7 pages and scroll through docs to get this 1 liner. It’s not going to cost you anything to add to readme.
I don’t know how many Linux users you have - but brew stats would give you some idea of number of folks who just need simple commands.

**Comment by dimitri** [comment]
> Don’t need to click through 6-7 pages and scroll through docs to get this 1 liner. It’s not going to cost you anything to add to readme.

Yeah writing docs is hard. Reading them is too. That example is almost exactly the one used in the last line of the current README file. I have opened a PR with improvements  to the current docs still, because I agree much improvements are needed.

Thanks for your contributions already, I hope for more to come!

**Comment by dimitri** [comment]
See also #1417

**Comment by johndpope** [comment]
nice - that's a million times better
 nb - this statement is actually containing triple backslash. so wont work.

` pgloader mysql://user@localhost/sakila postgresql:///pagila`

including the password is helpful

pgloader mysql://root:$MYSQL_ROOT_PASSWORD@localhost/sakila \
         pgsql://postgres:$POSTGRES_PASSWORD@localhost/pagila

**Comment by dimitri** [comment]
Yeah it will actually work. `postgresql://u@h/dbname` becomes `postgresql:///dbname` when omitting user and host both. Adding the passwords might be useful but connecting as root/postgres is frowned upon for security reasons: that's a lot more privileges than required.

**Comment by dimitri** [comment]
See also https://hub.docker.com/r/dimitri/pgloader/ where I reused your full example, because it's well adapted to the docker environment and commands.

**Comment by wweevv-johndpope** [comment]
that was my use case - thanks
