### ISSUE TITLE
feature request:use gzexe to compress the target binary if sbcl core do not compile with compression

### ISSUE THREAD

**Issue by amutu** [dimitri/pgloader#143]
I use gzexe compress pgloader from 120MB to 22MB.

**Comment by dimitri** [comment]
Please use SBCL feature to compress cores instead. What platform are you on?

**Comment by amutu** [comment]
I down load SBCL binary from the offical website.I use CentOS6,which do not have SBCL pkg.I do not want to compile SBCL myself.

**Comment by dimitri** [comment]
Ok, fair enough. Then I will close this issue has it being your choice not to depend on SBCL core compression facility, which pgloader's normal Makefile depends on. You could open a bug on the CentOS package so that they include the feature by default. It's about what we did in debian, ubuntu and brew, and now --with-core-compression is the default for SBCL on those systems.
