### ISSUE TITLE
pgloader Virtual Appliance

### ISSUE THREAD

**Issue by djbclark** [dimitri/pgloader#160]
Given how sensitive this software seems to be to its environment, perhaps it'd be a good idea to distribute it as a virtual appliance.

I'm not opening any of the below things as bugs as I've given up, and didn't keep good enough notes, but perhaps something here will be useful to someone:

(a) Mac OS X, kept getting dropped to some debugger with an error about being unable to open some dynlib file. It turns out that this was because I didn't have some software pgloader was dependent on (freetds?) that wasn't installed. I installed it via "brew", and then at least it didn't dump to debugger, but error messages like "Control stack guard page unprotected / CORRUPTION WARNING in SBCL" made me move on to...

(b) Windows 64-bit, where the complaint was that some 32-bit library didn't exist, moving to...

(c) One of the Linux distros there is a package for on the home page, Wheezy. However when one tries to install that package, one sees the package requires versions of other packages that do not exist in Wheezy. Also the slightly older version of pgloader that ships with Wheezy fails. So on to...

(d) Jessie, where there are issues with UTF-8. But at least it doesn't drop to debugger or anything! And I found an issue in this bug tracker confirming this was a pgloader bug, and with a fix, which lead me to wanting to recompile, but...

(e) The source requires debian packages that do not exist, even in unstable, like "cl-uuid". Coming at the compile via the bootstrap .sh, instead I find out that there is no packaged named "dh-lisp". With no other way (at least without learning all about an esoteric language ecosystem) to get the missing deps, and hours spent already, fail.

**Comment by dimitri** [comment]
Hi,

First, thanks for the time you've spend on pgloader so far and on the time you added on-top of that to report this issue. The distribution of pgloader is still very much work-in-progress, but I would have expected it to be way easier than that.

In terms of appliances, did you try to build a docker image as described in the INSTALL.md file? it contains my note of what I did to produce https://registry.hub.docker.com/u/dimitri/pgloader-3.1.cd52654/. You might want to try that one which is as far as an *appliance* goes for pgloader.

Now on to the more specific parts:

 1. it should be that pgloader doesn't need the freetds dylib at all unless you're connecting to a MS SQL database source, but that has been known broken and fixed, see #153 for details. Building on MacOSX should be as easy as `brew install sbcl && brew install freetds && make` (the freetds stuff is still required for building)

 2. I know about nothgin about windows, having never used it for work, so that's where it might be the most challenging to get things in order right now, although I have received feedback from users who got it working see #159 

 3. It turns out that my wheezy build environment is in fact polluted with things from sid so that I can publish packages to debian, sorry about that. The good parts is that pgloader is in fact available in debian directly, see https://packages.debian.org/sid/pgloader

 4. I'm not aware of those encoding issues in jessie...

 5. it's easier to build from source without the whole debian packaging at this moment because several of the build dependencies are in the NEW queue waiting for licensing approval, see also https://github.com/dimitri/ql-to-deb/tree/master/packages for the list of packages I spent time building so that we can have pgloader simply working in debian, without all the problems you're talking about.

**Comment by kidig** [comment]
Hi @dimitri,

2. It's work properly in Windows. But is needs some DLLs for runing:
    * _sqlite3.dll_ (downloaded from sqlite.org)
    * _libssl32.dll_ and _libcrypto.dll_ (I got it from Git for windows package that has already installed on my laptop).

Could you pack this files in zip-archive among with exe for next releases?
IMHO it would be useful for windows users.

**Comment by dimitri** [comment]
I'll see about that yes. What I would love to see happening tho would be to delegate the windows support to someone who actually uses the OS to boot. Who's up to be the pgloader windows version Release Manager then? ;-)

**Comment by dimitri** [comment]
Closing because of automated build as docker image at: https://hub.docker.com/r/dimitri/pgloader/
