### ISSUE TITLE
Mysql VARCHAR(32) UUIDs -> Postgres native UUIDs

### ISSUE THREAD

**Issue by willkessler** [dimitri/pgloader#274]
Wishlist:

Would love to have a translator to do this... currently using manual SQL.  If the contents of the mysql field were not a valid UUID, it would ideally try to null it out or assign a UUID with all zeroes.

(Would try to write this myself and contribute it but haven't done lisp in 25 years... but perhaps it'd be easy if there's an example or two you'd recommend starting with?)

**Comment by dimitri** [comment]
Should be quite easy, maybe using cl-ppcre (regexp) as you're trying to parse text content at this point I guess...

**Comment by dimitri** [comment]
I realize while cleaning-up the issues list that I failed to provide you with examples to follow. Have a look at the transform file, it's full of them:
  https://github.com/dimitri/pgloader/blob/master/src/utils/transforms.lisp

See the `--load-lisp-file` option for pgloader too.

**Comment by dimitri** [comment]
Reading that again some time later, did you try to add a cast to UUID without any transformation function? You didn't paste any example, it might just be that the data is compatible after all...

   cast column foo.bar to uuid drop typemod

Closing the issue in order to clean-up the list, please re-open if needed.
