### ISSUE TITLE
Is there a way to make pgloader update an existing record?

### ISSUE THREAD

**Issue by dzuluaga** [dimitri/pgloader#280]
I want to leverage pgloader to import data into a table which already has data. So, if the primary key already exists, I want to update any of the existing values with the data coming in a CSV file. Is that possible?

**Comment by dimitri** [comment]
It is not supported directly by pgloader, but what you can do is load into a work table then use the technique detailed in my blog at http://tapoueh.org/blog/2013/03/15-batch-update against that work table.

**Comment by Ramblurr** [comment]
Has this technique changed since the original poster asked?

**Comment by dimitri** [comment]
In 9.5+ you can maybe play with the `ON CONFLICT` clause as documented at https://www.postgresql.org/docs/current/static/sql-insert.html ; in order to avoid concurrency pitfalls. I will need to play with that and make another article.

**Comment by jeremybradbury** [comment]
Is is possible to maybe add a flag that adds `ON CONFLICT (pk) DO NOTHING` to the end of every insert?

this way we can get a similar effect as this request, allowing us to add only new items without trying to filter them first. 

we really shouldn't need ETL tools for either option (NOTHING/UPDATE). Esp when we can make a fun find/replace python, js, even selenium script to insert either clause at the end of each insert in post processing.

the only pre-requisite I see, for both, is knowing the primary key, which seems trivial in mysql, mariadb, etc
```
SELECT TABLE_NAME, COLUMN_NAME
FROM INFORMATION_SCHEMA.key_column_usage 
WHERE table_schema = "database_name" AND CONSTRAINT_NAME = "PRIMARY"
```
`database_name` being the only variable above, getting you a full list of all primary keys from all tables. 

you could do something similar with not PRIMARY condition for the `ON CONFLICT (pk) DO UPDATE` to list all fields besides the primary keys.

I realize the majority use case is a one time transition, but as it is now, the default of the entire transaction failing seems silly, when adding a clause to INSERT can allow us to upsert ignore and upsert overwrite, using a simple command line flag `--on-conflict=nothing/overwrite` (omit for the current default: "throw error and cancel transaction").

When i create PG queries they usually have an on conflict and when using tools to generate, like SequelPro or similar, those clauses are there. 

I understand this will not handle more complex upserts, but I think that's when some ETL is actually needed. Otherwise one of the other 3 options should serve everyone. Seems like low LOE to build, simple CLI interface for it, but lots of testing would be needed.

Anyway, I don't see this feature being added before we'd need it, so it's just an idea, and we'll likely have to find a manual find/replace or an automated regex based solution like I mentioned above.

I just spent some time with ctr-f `INSERT` and copy/pasting `ON CONFLICT (id) DO NOTHING` just above each one... and figured there has to be a better way than this every time we want to update the reporting database. eventually we can fully migrate and use realtime replication, but until we can fully replace a complex legacy app we're stuck using 2 engines.

**Comment by jeremybradbury** [comment]
in case this is useful for someone else, I was able to kinda solve my problem by using pgloader locally, then using pg_dump (version 12 or later for `--on-conflict-do-nothing`):

```
pg_dump --file 2021-08-12.sql --verbose --quote-all-identifiers --role "postgres" --format=p --section=pre-data --section=data --section=post-data --inserts --on-conflict-do-nothing --encoding "UTF8" --schema "public" "onstreambot"
```

i just have to do some "with insert where" magic in an intermediary database or temp table before i can create it... and yeah i still have to create it since my local (or a test server) and production won't be in sync OR it would be, but needing a much longer maintenance window. 

it would be just be nicer/cleaner/easier to automate, if this happened as it leaves mysql/maria/etc, before it enters postgres, but that would require pgloader to change how it works a bit, to match the more modern (12+) postgres API.

**Comment by ragapinilih** [comment]
> 

Any update on this?

**Comment by ragapinilih** [comment]
> In 9.5+ you can maybe play with the `ON CONFLICT` clause as documented at https://www.postgresql.org/docs/current/static/sql-insert.html ; in order to avoid concurrency pitfalls. I will need to play with that and make another article.

Any update on this?

**Comment by dwt** [comment]
I would really like support for `ON CONFLICT (pk) DO NOTHING` as it would greatly simplify doing multiple incremental migrations without having to clear out the tables each time.

Is there a chance to reopen this bug and track this behavior change here?
