### ISSUE TITLE
Create mapping tables with pgloader

### ISSUE THREAD

**Issue by waghanza** [dimitri/pgloader#292]
Hi,

I want to load huge amount of data in my `postgresql` database.
However, I want to load foreigns.
I my _input_ file I want to put a dynamic value.
For example, I already have in my database a row and I want to link this row with the inserted data.

* table `cities`, **already** in database

| id | name |
|--- | ------- |
| 1  | paris  |
| 2 | london |

* what I want to insert

| service | city |
|---- | -----|
| subway | paris |
| subway | london |
| cycle | paris |
| train | paris |
| bus | london |

* what I expect to be in my database

   * table `cities`

| id | name |
|--- | ------- |
| 1  | paris  |
| 2 | london |

   * table `services`

| id | city_id | service |
|--- | ------- | ---- |
|  1 | 1 (since `paris`) | subway |
| 2  | 1 (since `paris`) | cycle |
| 3 | 1 (since `london`)| train |
| 4 | 2 (since `london`)| subway |
| 5 | 2 (since `london`) | bus |

I do not know how to **dynamically**  _map_ between 
* 1 and `paris`
* 2 and `london`

Could `pgloader` help me ? By for example, defining a function before loading

**Comment by dimitri** [comment]
This is a classic limit of the ETL approach (*Extract*, *Transform* and *Load*) where the *Extract* step would need data from the database, which you don't have yet. That's why some people argue that it's better to do ELT (*Extract*, *Load* and *Transform*): in your case, load the data as is in a temporary table, and once done, fill the destination table from it with a `join` lookup to fill-in the foreign keys.
