### ISSUE TITLE
Adding timezone to naive datetime fields from MySQL

### ISSUE THREAD

**Issue by robhudson** [dimitri/pgloader#331]
Hi,

We have a MySQL database we are migrating to Postgres. All the datetime fields have no timezone and the server is PST. During data migration we would like to have these datetime fields automatically assume a PST timezone during data load. Is this possible?

I've tried a few things that didn't seem to work.

With:
`  SET client_timezone TO 'PST8PDT'`
the timestamps are the exact same time with `+00`.

With:
```
 BEFORE LOAD DO
 $$ CREATE SCHEMA IF NOT EXISTS public; $$,
 $$ SET TIMEZONE='PST8PDT'; $$;
```
the timestamps are also the exact same with `+00`.

The relevant `CAST` line in our command file is:
```
 CAST type datetime to timestamptz drop default drop not null using zero-dates-to-null,
```

Is there a way to achieve this via pgloader?

Our fallback is to import them without time zone and then do an `ALTER TABLE ... USING ... AT TIME ZONE 'PST8PDT'` after the fact so Postgres will convert them. I've tested this and this works. But it would be more ideal if we can take care of this during the load.

Thanks

**Comment by dimitri** [comment]
Can you try the following variant spelling:

    set timezone to 'PST8PDT'

As a pgloader clause. The SET in the `BEFORE LOAD` section is going to be run only in that context, and not in the worker threads that actually load the data into PostgreSQL.

**Comment by robhudson** [comment]
That was easy. :) That worked exactly how I was expecting. Thanks.

Might this be something that is added to the documentation? I found another github issue asking a similar question.

**Comment by dimitri** [comment]
Well it's more of a PostgreSQL question really... let's say that I would accept a documentation patch covering it ;-)

**Comment by medley-unavco** [comment]
Has this changed since this issue was closed? I've tried all the suggested syntax. 
`client_timezone` is unrecognized and
```
SET timezone to 'UTC' 
```
successfully runs but I still get local timezones from my `RUN AFTER LOAD` clauses.

**Comment by brian-pond** [comment]
I've got a similar (but slightly different) issue:

* My source MySQL (MariaDB) database has datetime columns, all naive.
* I definitely want them to have a TZ in PostgreSQL.  The time zone offset should always be US/Eastern.
* However, my development machine's time zone is US/Pacific.

**pgloader** does successfully apply a time zone to all my datetime columns.  :heavy_check_mark: 
However, it's applying the wrong offset.  It's applying a Pacific Time offset, instead of Eastern (see screenshot)  :confused:  

Things I've tried:
* Setting environment variable `PGTZ=US/Eastern`
* Adding `SET timezone to 'US/Eastern'` in the pgloader command file (see below)

----
#### Command File
```
LOAD database
     from    mysql://foo:bar@127.0.0.1:3313/baz
     into    postgresql://postgres:foo@127.0.0.1:5432/bar

SET MySQL PARAMETERS
 net_read_timeout  = '120',
 net_write_timeout = '120'

WITH include drop, create tables, no truncate,
     create indexes, reset sequences, foreign keys,
     workers = 6, concurrency = 1

SET timezone to 'US/Eastern'

CAST type datetime to timestamptz
     drop default
     drop not null
     using zero-dates-to-null,
     
     type date
     drop default
     drop not null
     using zero-dates-to-null

INCLUDING ONLY TABLE NAMES MATCHING 'tabCustomer'

BEFORE LOAD DO
  $$ create schema if not exists v13devdb; $$;
```

![image](https://user-images.githubusercontent.com/19827963/219982492-abe43099-8c58-4856-a656-3b4a5b84fd34.png)
