### ISSUE TITLE
Document when/how to use the bundled distribution, and where to find it.

### ISSUE THREAD

**Issue by davidklebanoff** [dimitri/pgloader#394]
It's really unclear where to find the bundled distribution version and there is no mention of it in any of the documentation. I was only able to find a link to it by digging through the issues.

Downloading the version from the release page didn't seem to contain it?:
https://github.com/dimitri/pgloader/archive/v3.3.0.50.tar.gz

But this link I found does?:
http://pgloader.io/files/pgloader-bundle-3.3.0.50.tgz

My apologies if I'm missing something.

**Comment by dimitri** [comment]
You're right, the bundle is still experimental and is made for RPM packagers so that they don't have to deal with pgloader build dependencies, and also for some environment where it's not possible to download non certified artefacts at build time.

As it's still experimental it's not properly addressed yet in the docs etc. Will work on that at next release where I intend the bundle to be an official one. Also, I should release more often... but the current situation with the new parallelism and the frozen loads looks like a blocker to me.

**Comment by dimitri** [comment]
The current release is now officially including the bundle and it's used already in the RPM packaging of pgloader. Closing the issue, feel free to open again if necessary.
