### ISSUE TITLE
Create index concurrently in Postgres?

### ISSUE THREAD

**Issue by AndreaCrotti** [dimitri/pgloader#401]
I notice that most of the time (for a big 11million rows table) is spent building indexes, and it's blocking on it.
From what I see it should be at least parallel with the data but it doesn't look like it is, since the rows are all there while it still copies stuff..

    (defun create-indexes-in-kernel (pgconn table kernel channel
    				 &key (label "Create Indexes"))
      "Create indexes for given table in dbname, using given lparallel KERNEL
       and CHANNEL so that the index build happen in concurrently with the data
       copying."
      (let* ((lp:*kernel* kernel))

Postgres has the "CREATE INDEX CONCURRENTLY" feature which solves the blocking issue, is there any reason not to use it?
Is there a way to try that with the current implementation or I need to change the code?

**Comment by dimitri** [comment]
It's only possible to have a single `CREATE INDEX CONCURRENTLY` command in flight in PostgreSQL, because the concurrency here is against DML usage (INSERT, UPDATE, DELETE queries). What pgloader wants is for all the `CREATE INDEX` to happen concurrently to one another, thus incurring a single Sequential Scan of the table.

The comments are misleading you in this case, the index are built altogether concurrently to data copying activity on *other* target tables.

The most efficient way to build an index is in bulk against the data when it's all available, so that's what we do in pgloader.
