### ISSUE TITLE
how to run java programme through load file of pgloader

### ISSUE THREAD

**Issue by navengp** [dimitri/pgloader#464]
Hi 
can we ruin the java programme from .load file,is there any option like that in pgloader?

Regards
Naveen

**Comment by mltsy** [comment]
I'm new to pgloader as well, but I know it is a lisp program that compiles to a binary... can you be more specific about what you're trying to do? (I'm not familiar with a ".load" file)  If you can describe in more detail maybe someone could provide more help.

Are you asking whether you can run the program without compiling it?  (with an interpreter, for instance?)  I don't see that described anywhere in the README, so I would assume not, since the README does list several ways to install and run the program... (but I know nothing about lisp)

**Comment by dimitri** [comment]
@navengp it should be possible to use ABCL and have pgloader loaded in a JVM, if that's what you are asking for. See http://abcl.org and http://abcl.org/trac/ticket/405.
