### ISSUE TITLE
uiop:run-program :directory

### ISSUE THREAD

**Issue by pipping** [dimitri/pgloader#472]
Hi,

I was looking at how different projects on quicklisp use `uiop:run-program` and came across the snippet
```common-lisp
      (let ((git-hash `("git" "--no-pager" "log" "-n1" "--format=format:%h")))
        (uiop:with-current-directory ((asdf:system-source-directory :pgloader))
          (multiple-value-bind (stdout stderr code)
              (uiop:run-program git-hash :output :string)
            (declare (ignore code stderr))
            stdout)))
```
in pgloader. I only wanted to point out that `run-program` also accepts a `:directory` parameter.

PS: I was a bit surprised that src/params.lisp passes the command as a list of strings to `run-program` while src/utils/archive.lisp uses a string generated via `format nil`. The former allows `run-program` to bypass the shell while the latter implies `:force-shell t`.

**Comment by dimitri** [comment]
Hi, thanks for having a look at pgloader code!

In one case we use the command `"gunzip -c ~s > ~s"` in `src/utils/archive.lisp`, I believe that's why I settled on using strings there ; and also to be able to more easily use `log-message` on those strings (although the use of the `~{~a~^ ~}` format string would certainly solve it).

If you're up for a pull request that would generalize the `:directory` usage of `uiop:run-program` I would certainly accept it! ;-)

**Comment by pipping** [comment]
Ah, yes; I missed the ">" in there. Although that could of course also be addressed through `(run-program :output "/path/to/file")` -- you might even prefer this way because it allows you to specify `:if-output-exists :append/:supersede/:error` and the likes (*).

PR coming your way in a few minutes.

(*) Truth be told the changes that make that world as nicely and nicely as I'd like have not made it onto the master branch but not into a release yet.

**Comment by pipping** [comment]
It's PR #473 now (completely untested, I must caution!).

**Comment by dimitri** [comment]
Thanks! See my comments on the PR, I'm now worried I accepted it too hastily...
