### ISSUE TITLE
Make hangs on sbcl 1.0 - Makefile to blame

### ISSUE THREAD

**Issue by otheus** [dimitri/pgloader#479]
I was trying to compile the latest version from git repo on an older RHEL 6 install, which has no later than sbcl 1.0.38. This turns out to be a moot point since pretty much no version of this software will compile for it.

The `COMPRESS_CORE` option determiner causes make to completely hang. Why? because at that point, `sbcl` did not yet support the `--quit` option, and that causes the script to drop to debug mode. See https://bugs.launchpad.net/sbcl/+bug/822712

The following patch takes care of this:
```
diff --git a/Makefile b/Makefile
index 2539801..9994e1a 100644
--- a/Makefile
+++ b/Makefile
@@ -50,9 +50,8 @@ endif

 ifeq ($(CL),sbcl)
 COMPRESS_CORE ?= $(shell $(CL) --noinform \
-                               --quit     \
-                               --eval '(when (member :sb-core-compression cl:*features*) (write-string "yes"))')
-
+                               --eval '(when (member :sb-core-compression cl:*features*) (write-string "yes"))' \
+                               --eval '(quit)')
 endif

 # note: on Windows_NT, we never core-compress; see above.
```

**Comment by otheus** [comment]
Note, other problems may abound.

**Comment by dimitri** [comment]
Would you ask PostgreSQL developers to support compiling the current project code with gcc 2.95 or something from this era? It's basically equivalent to trying to use SBCL 1.0.38 today... Please upgrade, really.

**Comment by otheus** [comment]
Hi Dmitri,

First, all the other code in the Makefile uses the `--eval '(quit)'` semantics. Only on this one case is it broken. Second, I'm using the latest SBCL available for the given platform.  Third, one of the use cases for your wonderful tool is the ability to transfer databases that have been sitting for quite some time.  Finally, I'm not sure the analogy fits. Postgresql tries to be cross-platform and is written in C which is stable. But yes, when I compile projects for distribution, I try to see that I can compile it on the target platform.

**Comment by dimitri** [comment]
It used to be that SBCL would use `(sb-ext:exit)` to exit rather than `(quit)`, so in your case I am surprised it works. I could make the change for all the call sites, but really, I don't want to pretend like I care supporting too old releases of SBCL: pgloader will break in many other cases and I won't have time to reproduce and try to understand them, let alone fix them.

Please do consider getting a supported version of SBCL for your platform directly from http://www.sbcl.org/platform-table.html as it looks like our packagers of choice are not making a good job here.
