### ISSUE TITLE
Possible to add fillfactor support?

### ISSUE THREAD

**Issue by mfn** [dimitri/pgloader#516]
Is it possible to add a fillfactor to a table?

From the [documentation](https://www.postgresql.org/docs/9.6/static/sql-createtable.html):
> The fillfactor for a table is a percentage between 10 and 100. 100 (complete packing) is the default. When a smaller fillfactor is specified, INSERT operations pack table pages only to the indicated percentage; the remaining space on each page is reserved for updating rows on that page. This gives UPDATE a chance to place the updated copy of a row on the same page as the original, which is more efficient than placing it on a different page. ...

The syntax is:
```SQL
CREATE TABLE .... WITH (fillfactor=n);
```

It's also possible adjust a table after it has been created:
```SQL
ALTER TABLE .... SET (fillfactor=n);
```

I tried to find something in the docs without luck and looking into https://github.com/dimitri/pgloader/blob/master/src/pgsql/pgsql-ddl.lisp#L39-L62 I couldn't make it out.

The docs state:
- `BEFORE LOAD`<br>and
- `AFTER LOAD`

However:
- `BEFORE LOAD` is applied even *before* the table has been created, not just before the data is loaded
- `AFTER LOAD` is already to late; to be efficient, the fillfactor must be set before data is imported otherwise `VACUUM FULL` or `CLUSTER` has to be run on a table which is undesired for big tables.

Or maybe its possible and I just missed it?

Thanks

**Comment by dimitri** [comment]
Yeah the `BEFORE LOAD` run before anything happens, it allows to create a schema in which to create the target tables for instance. So maybe we need to have another set of hooks, but I would appreciate if we could keep the current one with its semantics ; or we need a syntax to add options to tables that are going to be created.

My guess is that a specific syntax for the _storage options_ (`fillfactor` being one of them) is best here, because you certainly want to apply it to table names that are going to be discovered at run time for pgloader. So I would think that the best option here is to have a new pgloader `ALTER TABLE NAMES MATCHING` clause and operation.

    ALTER TABLE NAMES MATCHING ~/./ SET (fillfactor=40);

**Comment by mfn** [comment]
Yes, a facility for the storage option sounds great!

**Comment by mfn** [comment]
In a similar vein, would it be possible to add additional columns *after* the table has been created by pgloader?

I.e. only new columns in the destination postgres database table, no in the source (e.g. MySQL).
