### ISSUE TITLE
RPM for PGLoader installation in CentOS based system

### ISSUE THREAD

**Issue by jaseenal** [dimitri/pgloader#535]
I am looking to get rpm package or a script to build rpm for PGLoader installation in CentOS based system (Amazon Linux). Can you please advise.

**Comment by dimitri** [comment]
What happens when you try either of those scripts:

  https://github.com/dimitri/pgloader/blob/master/bootstrap-centos.sh
  https://github.com/dimitri/pgloader/blob/master/bootstrap-centos7.sh

And then the provided spec file and/or the specific Make target for building the RPM?

  https://github.com/dimitri/pgloader/blob/master/pgloader.spec
  https://github.com/dimitri/pgloader/blob/master/Makefile#L206

Also, did you have a look at https://yum.postgresql.org which contains packaged version of pgloader for RPM based systems?
