### ISSUE TITLE
operator does not exist : smallint = boolean

### ISSUE THREAD

**Issue by utkgarg** [dimitri/pgloader#559]
I am migrating my Django project from MySQL to PostgreSQL. After migrating with the help of pgloader, I get the following error:

![db_error](https://cloud.githubusercontent.com/assets/25474580/26396691/92afdec4-4091-11e7-836b-40c61663b4ab.png)

The SQL query is as such:

> SELECT COUNT(*) AS "__count" FROM "topics_topic" WHERE ("topics_topic"."status" = 3 AND "topics_topic"."is_purged" = false AND "topics_topic"."public" = true)

**'topics_topic'** is table name and **"public"**, **"is_purged"** and **"status"** are column names.
Does it have anything to do with 0 and 1 not being converted to False and True respectively?

**Comment by dimitri** [comment]
I think you need to 1. learn about the boolean data type that we have in PostgreSQL and doesn't exist in MySQL and then 2. either adapt your code (Django might make it easy but I don't know) or add a CAST rule to your migration command / `ALTER TABLE` so that you're using integers rather than booleans again.

My advice is to learn about SQL booleans and use them.
