### ISSUE TITLE
Encoding problem transforming mysql latin1_swedish_ci to postgresql

### ISSUE THREAD

**Issue by jandm123** [dimitri/pgloader#665]
I am using pgloader to transform a mysql database with latin1_swedish_ci encoding to postgresql.
It looks like some characters are incorrectly decoded:

"Rož?avská, 821 04 Bratislava, Slovakia" (mysql) -> "Ro?avská, 821 04 Bratislava, Slovakia" (postgres)

Is pgloader taking into account that mysql uses this particular collation ?
When i first convert the mysql database to utf8, everything seems to work fine, but i would like to avoid this step if possible.

**Comment by dimitri** [comment]
So you're saying that the source data `Rož?avská` is correctly encoded? Maybe there's a glitch when copy/pasting it here, tho. Well there are several ways to control the MySQL encodings in use in queries, and 3 settings are used at any time.

See the *DECODING TABLE NAMES MATCHING* clause of the pgloader command, and also the MySQL settings with the *SET MYSQL PARAMETERS* clause. If all fail, then converting to UTF8 using the MySQL tools might be your best course of action here.

**Comment by jandm123** [comment]
You are right of course: Rož?avská should have been Rožňavská. Anyhow, i was expecting it to remain the same after conversion. I will try your suggestions, thanks !

**Comment by nick-solly** [comment]
I think I may be experiencing a similar issue and I believe it may be related to the fact that MySQL's latin1 is in reality the Windows cp1252 character set (https://dev.mysql.com/doc/refman/8.0/en/charset-we-sets.html).

Code points between 0x80 and 0x9f are undefined in latin1 but are used in cp1252.

I'm also migrating between a latin1 MySQL and UTF-8 Postgresql and am finding that it's these 27 code points which are not migrating correctly.  For example the Euro Sign (0x80) is being migrated as (0xC2 0x80) rather than the expected (0xE2 0x82 0xAC).

Any support much appreciated.

**Comment by dimitri** [comment]
@nick-solly did you try using the clause`DECODING TABLE NAMES MATCHING` yet? See the docs about it at https://pgloader.readthedocs.io/en/latest/ref/mysql.html#mysql-encoding-support

**Comment by nick-solly** [comment]
Thanks for the quick reply @dimitri.  I'm using the following load file:

```
load database
   from mysql://***:***@localhost/qrhubbase
   into pgsql:///qrhubbase
   with create no tables, disable triggers, preserve index names
   decoding table names matching ~/.*/ as CP1252
   alter schema 'qrhubbase' rename to 'public';
```
I've run pgloader with the `--debug` flag but the output is pretty large. Where should I be looking to see if the `DECODING TABLE NAMES` is having an effect?

My euro symbol test value, which is like this in MySQL...

```
mysql> select hex(report) from resttest_car where prod=128;
+-------------+
| hex(report) |
+-------------+
| 80          |
+-------------+
1 row in set (0.01 sec)
```
...is still coming over like this in Postgresql...
```
qrhubbase=# select encode(report::bytea,'hex') from resttest_car where prod=128;
 encode
--------
 c280
(1 row)
```

**Comment by dimitri** [comment]
What are your PostgreSQL database encoding and client_encoding settings when you run that query?

**Comment by nick-solly** [comment]
UTF-8 all around:

```
qrhubbase=# SHOW SERVER_ENCODING;
 server_encoding
-----------------
 UTF8
(1 row)

qrhubbase=# SHOW CLIENT_ENCODING;
 client_encoding
-----------------
 UTF8
(1 row)

qrhubbase=# \l
                             List of databases
   Name    |  Owner   | Encoding  | Collate | Ctype |   Access privileges
-----------+----------+-----------+---------+-------+-----------------------
 postgres  | postgres | SQL_ASCII | C       | C     |
 qrhubbase | nick     | UTF8      | C       | C     |
 template0 | postgres | SQL_ASCII | C       | C     | =c/postgres          +
           |          |           |         |       | postgres=CTc/postgres
 template1 | postgres | SQL_ASCII | C       | C     | =c/postgres          +
           |          |           |         |       | postgres=CTc/postgres
(4 rows)
```

**Comment by nick-solly** [comment]
Load file:
```
$ cat qrhubbase_dataonly.load
load database
   from mysql://djangouser:5turnips@localhost/qrhubbase
   into pgsql:///qrhubbase
   with create no tables, disable triggers, preserve index names
   decoding table names matching ~/.*/ as CP1252
   alter schema 'qrhubbase' rename to 'public';
```
Running using:
```
$ pgloader --verbose --debug qrhubbase_dataonly.load > pgl.log
```
I don't find any instances of "force encoding" in the log:
```
$ grep -i 'force encoding' pgl.log
$
```
So I'm guessing it's not respecting the `decoding table names matching ~/.*/ as CP1252` instruction.

I don't understand why though as the regex should select all tables, right?

**Comment by dimitri** [comment]
Oops, I've left bugs in around the DECODING AS support code. The patch I just pushed should be fixing the matching again, can you please compile from sources and try again?

**Comment by dimitri** [comment]
You're comparing encoding support in SBCL and CCL, not in different versions of pgloader. I think CCL is lacking the CP1252 encoding here, and you might want to compile with SBCL instead then.

**Comment by nick-solly** [comment]
@dimitri it worked!!

I can see the `Force encoding` messages in the log and now my euro test character:

```
qrhubbase=# select encode(currency_sign::bytea, 'hex') from expense_currency where id=3;
 encode
--------
 e282ac
(1 row)
```

Perfect!

Once again, many thanks for the time you've spent helping me on this.  Hopefully this may prove useful to others in the future trying to migrate a MySQL Latin1 (which is actually CP1252) database to UTF8 Postgresql.

**Comment by TylerHorn** [comment]
For anyone coming across this issue and are running the docker container compiled with CCL instead of SBLC due to GC running out of heap. Unfortunately the CCL build does not include support for CP1252 encoding. In my case I wasn't using any characters from 128 - 159 (ie. Euro symbol, Trademark, etc.) I was able to use the ISO-8859-1 encoding.

Here is a link to a breakdown of the character differences between [CP1252 and ISO-8859-1](https://www.w3schools.com/charsets/ref_html_8859.asp)

I was able to resolve this issue with the following load file:
```
LOAD DATABASE
   FROM mysql://pgloader@mysql/development
   INTO postgresql://pgloader@postgresql/development

...

SET search_path to 'development'

DECODING TABLE NAMES MATCHING ~/.*/ AS ISO-8859-1

ALTER SCHEMA 'development' RENAME TO 'public';
```

I hope that this can help guide anyone running into this combination of issues.
I personally spent way too much time trying to figure this out when migrating from MySQL 5.7 (latin1 encoded) to PostgreSQL 14 (utf8 encoded). 


P.S.
Thanks to everyone that previously worked on debugging this issue!
