### ISSUE TITLE
sbcl 1.4.2+ error

### ISSUE THREAD

**Issue by kxjhlele** [dimitri/pgloader#708]
```
debugger invoked on a ASDF/ACTION:CIRCULAR-DEPENDENCY in thread
#<THREAD "main thread" RUNNING {1001B78083}>:
  Circular dependency:
     ((#<ASDF/LISP-ACTION:LOAD-OP > . #<ASDF/SYSTEM:SYSTEM "simple-date">)
      (#<ASDF/LISP-ACTION:LOAD-OP >
       . #<ASDF/SYSTEM:SYSTEM "simple-date-postgres-glue">)
      (#<ASDF/LISP-ACTION:LOAD-OP >
       . #<ASDF/COMPONENT:MODULE "simple-date-postgres-glue" "simple-date">)
      (#<ASDF/LISP-ACTION:LOAD-OP >
       . #<ASDF/LISP-ACTION:CL-SOURCE-FILE "simple-date-postgres-glue" "simple-date" "cl-postgres-glue">)
      (#<ASDF/LISP-ACTION:PREPARE-OP >
       . #<ASDF/LISP-ACTION:CL-SOURCE-FILE "simple-date-postgres-glue" "simple-date" "cl-postgres-glue">)
      (#<ASDF/LISP-ACTION:PREPARE-OP >
       . #<ASDF/COMPONENT:MODULE "simple-date-postgres-glue" "simple-date">)
      (#<ASDF/LISP-ACTION:PREPARE-OP >
       . #<ASDF/SYSTEM:SYSTEM "simple-date-postgres-glue">))

Type HELP for debugger help, or (SB-EXT:EXIT) to exit from SBCL.
```

enhancement: ASDF updated to 3.3.1. The ASDF release is dedicated to the late Elias Pipping who put enormous amounts of work into it despite his terminal illness. Thank you and rest in peace. (#1681201)

**Comment by dimitri** [comment]
This is due to a problem with current ASDF version as shipped by most recent SBCL versions. The problem should be solved at the `simple-date-postgres-glue` ASDF file level, if I understand correctly. See https://github.com/marijnh/Postmodern/commit/0d0667f141a984f0112f0fad4843297fca212e01 that contains the fix we need, IIUC.

You can try to git clone the Postmodern project in `build/quicklisp/local-projects` in the pgloader tree and build again.

**Comment by kxjhlele** [comment]
thx
