### ISSUE TITLE
problem with search_path setting on postgresql

### ISSUE THREAD

**Issue by machytkafitanalytics** [dimitri/pgloader#718]
Hi,
I built latest pgloader from sources (pgloader version "3.4.572f6a3" compiled with SBCL 1.4.3.236-cfa129e) to replace our old versions because we switched to MySQL 5.7 and old pgloaders had "group by" errors when data are loaded from MySQL 5.7. Plus I needed "quote identifiers" repaired (see issue #703). We load data once per day from MySQL to PostgreSQL. Generally everything works OK and I thank you for all fixes. 

But now we have encounter strange problems with "search_path" setting. In pgloader command file I use setting " search_path to 'upload' ". And after pgloader finished we have found errors in some older apps which for some reason (I do not know why because it is bad practice) do not use full table name with schema ("schema"."table") but rely on "search_path". I checked settings on pg database and I see this in pg_settings on the given database:
```
db=# select name, setting, boot_val, reset_val from pg_settings where name = 'search_path';                                                                                                              
    name     |     setting      |    boot_val     |    reset_val     
-------------+------------------+-----------------+------------------
 search_path | upload, upload | "$user", public | upload, upload
(1 row)
```
Looks like pgloader changed global setting for this database and even "reset_val". When I try to reload configuration ("select pg_reload_conf()") I see no effect. The same when I try to use "alter database ... set search_path ..." or "alter database ... reset search_path" - no effect either and I still see values set by pgloader. Which is actually quite funny... I checked it on several our databases where we already use latest pgloader and it is the same everywhere.

We fixed those other apps so we bypass these problems but generally there is something wrong about how search_path is set - this should be done for session only. Fortunately I do not see similar problems with other PG settings I change in pgloader command file - they seem to be used for session only which is OK.

**Comment by dimitri** [comment]
Hi, thanks for your detailed report.

In pgloader now when migrating from MySQL to PostgreSQL the `search_path` is altered thanks to the command `ALTER DATABASE ... SET search_path TO ...`, that you can see in verbose mode. We do that because some users are failing to find their data after migration otherwise.

All the database schema that are targeted by the pgloader migration are now appended to the database current `search_path` value, as obtained with the following SQL statement:

```sql
SELECT name FROM unnest(pg_catalog.current_schemas(false)) as t(name);
```

See https://github.com/dimitri/pgloader/commit/db7a91d6c413e43247e0661592727a4f4b8fdcfc for more details.

It's unclear to me what's the next step to solve your issue here. It might be that your best move would be to consider using `ALTER DATABASE ... SET` or other such commands to manage your `search_path`?

Also, how come pgloader doesn't see the proper `search_path` when running the SQL query above in your case?

**Comment by machytkafitanalytics** [comment]
Well, after some testes I understand that our setting of search_path in pgloader command file was an unfortunate relic of pgloader 3.1.x configuration - that old version loaded data based on search_path. 
Now I see that in context of latest version of pgloader it was a nonsense. OK, I repaired it the same way it happened - setting required search_path in this command file and removing it from cf after run. 
I must say I like new commands in 3.4.x versions allowing me to better manipulate with schema name etc. So as far as I am concern this issue can be closed. Thanks.
