### ISSUE TITLE
CSV parsing errors not in the error log

### ISSUE THREAD

**Issue by reist** [dimitri/pgloader#720]
The split between CL parsing and DB parsing is a bit odd.
The error log/dat files record all database errors, but code-level parsing issues only get logged into the main logfile, even though they may still be data problems.

Example structure: `CREATE TABLE text_issues (id integer, message text);`
Data line: `32<tab>"bad" quoting`
Command file:
```
LOAD CSV
 FROM 'bad.tsv'
 INTO postgresql://reist@localhost/main?text_issues
 WITH
  fields terminated by '0x9',
  fields optionally enclosed by '"'
;
```
Running this will cause cl-csv to error out with the following:
```
2018-01-17T15:35:26.025259Z ERROR We finished reading a quoted value and got more characters before a separator or EOL 9
32      "bad" quoting
```

Would it be possible to make these kinds of errors be logged in the log/dat files?

**Comment by dimitri** [comment]
Currently it's a design decision that the log files contain errors reported by PostgreSQL. I see why you'd want to find pgloader read-time errors in the log files too, but the problem is that we read-time errors, we can't append the data in the proper format in the `dat` file (because if we fail to read, we can't then reformat).

So we would have to put the input buffer/line into the log file along with the error message. Would that be a good fix for you?

**Comment by reist** [comment]
Oh, I see. That makes a lot of sense.
I don't think it's a good idea - some bugs or input issues may cause thousands of such lines. Also, nothing promises the input is short - in our case each line was measured in KB.
I'll rework the automatic parsing/reporting we have to use the main log file instead.
