### ISSUE TITLE
Database error 22P02: invalid input syntax for integer

### ISSUE THREAD

**Issue by pabace** [dimitri/pgloader#733]
Hello,
I'm currently working on pgloader version:

>  3.4.a603cd8 compiled with SBCL 1.4.3

And running 95 .load files that are loading from CSV and a few of them are giving the error:

> Database error 22P02: invalid input syntax for integer

For example in "asist.tiplis.load":
Database error 22P02: invalid input syntax for integer: 1 CONTEXT: COPY tiplis, lnea 1, column cod: 1

Column cod is integer and csv data is also integer at that column.

Debug didn't help.
I've been looking for solutions through google and reported issues.
Testing with several diferent options and changing data also, but always getting the same error.

I'm attaching the necesary files to reproduce the error
It would be highly appreciated if anyone can give it a look.

[asist.tiplist.zip](https://github.com/dimitri/pgloader/files/1668770/asist.tiplist.zip)

Thanks in advance,
Pablo

**Comment by dimitri** [comment]
So when using the `--client-min-message data` option, I can see that in the pgloader logs:

```
2018-01-27T16:18:32.145372+01:00 DATA > "ï»¿1	'Licencia por Enfermedad c/PromLic.Enf.c/Prom'	'I'	E	'C'	1	0	0	0	0	0	'N'	1
"
```

So then let's have a serious look at the file itself:

```
$ hexdump -C asist.tiplis.csv 
00000000  ef bb bf 31 3b 27 4c 69  63 65 6e 63 69 61 20 70  |...1;'Licencia p|
00000010  6f 72 20 45 6e 66 65 72  6d 65 64 61 64 20 63 2f  |or Enfermedad c/|
```

This looks like the UTF-8 Byte Order Mark as in https://en.wikipedia.org/wiki/Byte_order_mark#UTF-8 ; and the wikipedia page goes on to say:

> The UTF-8 representation of the BOM is the (hexadecimal) byte sequence 0xEF,0xBB,0xBF. A text editor or web browser misinterpreting the text as ISO-8859-1 or CP1252 will display the characters ï»¿ for this.

I just tried adding `WITH ENCODING UTF-8` to your pgloader command, which I recommend always doing, but even then it seems pgloader doesn't know how to deal with the UTF-8 BOM at this point. Can you make it so that the BOM isn't present on your files, while I'm going to have a look at how to deal with that properly from pgloader's end?

**Comment by pabace** [comment]
It worked encoding CSV file in UTF-8 without BOM!

Thanks again for your help!
