### ISSUE TITLE
Issue with Data formatting 

### ISSUE THREAD

**Issue by sanjum080816** [dimitri/pgloader#788]
Hello,

Currently we are trying sqlloader approach on pgloader as a part of migration .

As you can see below in sqlloader we can use  **substring , COALESCE (NVL in oracle) and SEQUENCE(MAX, 1 ) -->( which inserts MAX+1 value to the column specify) **  function or any other function before loading the data , 

```
OPTIONS (SKIP = 1)
LOAD DATA
TRUNCATE
INTO TABLE1
fields terminated by "@"
TRAILING NULLCOLS
(
    A,
    B,
    C "substr(:C,1,5)",
    D,
    E"NVL(:E,'XXXX')"
    F "SEQUENCE(MAX,1)", 
)
```

Is there any similar approach in pgloader ?

**Comment by dimitri** [comment]
Yes, see http://pgloader.readthedocs.io/en/latest/ref/csv.html and the examples in the source repository at https://github.com/dimitri/pgloader/tree/master/test ; several of them use transformation function in their target columns. In pgloader the notion is named a _projection_, by the way.

You can also write your own projection using any lisp code, including dynamically loaded function with the `--load-lisp-file` option. An equivalent projection to your example for pgloader looks like the following:

```
  INTO PostgreSQL://host:port/dbname
  (
    a,
    b,
    c text using (subseq c 1 5),
    d,
    e text using (or e "XXXX")
  )
```

About the sequence, use PostgreSQL sequence as a default value and just omit the column altogether in the loading, so that the default value is used.

**Comment by esoni** [comment]
Hi @dimitri ,
`  INTO PostgreSQL://host:port/dbname
  (
    a,
    b,
    c text using (subseq c 1 5),
    d,
    e text using (or e "XXXX")
  )`

great !!! I want to replace oracle function used in sql loader.
substr => subseq
nvl(e, "XXXX") => or e "XXXX"
Do you have  a list of all the operators available ? Is there also a correspondent to DECODE function ? 

Thanks a lot;

ps: i really love your postgres book !!
