### ISSUE TITLE
Auto conversion of date format delimiters in pgloader. 

### ISSUE THREAD

**Issue by NoelJoseph94** [dimitri/pgloader#830]
Hi.
I am facing an issue with the date format specifier in pgloader. In the .load file, if the date format is specified as [date format 'YYYY-MM-DD 'HH24:MI:SS'], and the incoming data in the data file is '2018/09/10 12:23:45' ,  the record does not error out. Instead the format is converted to the date format specified in the .load file before being loaded into the target table. Below is the scenario:

My sample load file:

![image](https://user-images.githubusercontent.com/43058948/45341144-1a51a100-b5b7-11e8-8acf-34350e3ca0b2.png)

sample data file:
![image](https://user-images.githubusercontent.com/43058948/45341259-9ea42400-b5b7-11e8-9622-7a5fa17b81dc.png)

Obtained output:
![image](https://user-images.githubusercontent.com/43058948/45341309-cc896880-b5b7-11e8-8d0c-c54fff8b5687.png)

The data in target table ( that got auto converted)-
![image](https://user-images.githubusercontent.com/43058948/45341380-1a9e6c00-b5b8-11e8-836a-09af2d31d8c0.png)

Expected output:
The process should error out, pushing these records which violate the format to the default error file.

Version -
![image](https://user-images.githubusercontent.com/43058948/45362694-23f8fa00-b5f3-11e8-81dd-482d8dc38156.png)

Can you please suggest what has to be done to get the required output.
Thanks.

**Comment by NoelJoseph94** [comment]
Hi Dimitri,
Any luck on this?

**Comment by dimitri** [comment]
Hi @NoelJoseph94 ; the current date format parser in pgloader doesn't care about the separators at all, as seen in the code at https://github.com/dimitri/pgloader/blob/master/src/parsers/date-format.lisp. That makes it easier to achieve decent performances. You will note that the parser generate a _format spec_ from the input string, and that the spec is used in the function `parse-date-string`. This specification only cares about the data, not the separator. Those are considered _noise_ int the data input stream.

``` lisp
CL-USER> (pgloader.parse-date::parse-date-format "YYYY-MM-DD HH24:MI:SS")
((:YEAR 0 4) (:MONTH 5 7) (:DAY 8 10) (:HOUR 11 13) (:MINUTE 14 16)
 (:SECONDS 17 19))

CL-USER> (pgloader.parse-date::parse-date-string
          "2018/09/10 12:23:45"
          (pgloader.parse-date::parse-date-format "YYYY-MM-DD HH24:MI:SS"))
"2018-09-10 12:23:45"
```

I though it would be good news that pgloader doesn't care about the input date using a slash rather than a dash to separate years and months. In what scenario would you want pgloader to reject data that it can make sense of?
