### ISSUE TITLE
MYSQL-INSUFFICIENT-CAPABILITIES

### ISSUE THREAD

**Issue by jlaffaye** [dimitri/pgloader#95]
With pgloader version "3.0.99" and LOAD DATABASE from a MySQL server version 5.0.51a, I got:

An unhandled error condition has been signalled:
   Condition QMYND:MYSQL-INSUFFICIENT-CAPABILITIES was signalled.

**Comment by dimitri** [comment]
I'm still dubious about a MySQL server lacking the capability to return how many rows where found in the resultset, so I'm closing this to clean-up open issues a bit. If that's still a problem that you want to see fixing, consider opening again with some ways to assess how common is such a setup.

**Comment by pinaraf** [comment]
I think there is a misunderstanding about what this capability does.
https://dev.mysql.com/doc/internals/en/capability-flags.html : «CLIENT_FOUND_ROWS : Send found rows instead of affected rows in EOF_Packet»
It does not mean the server is not able to tell how many rows are returned by a given query. It only changes the meaning of a field in the EOF packet, not even the OK Packet sent after each query. Are you really sure you use that flag in that packet ?

**Comment by dimitri** [comment]
In the driver at https://github.com/qitab/qmynd/blob/master/src/mysql-protocol/response-packets.lisp#L40 we see that the EOF packet is fully taken into accounts, as described in https://dev.mysql.com/doc/internals/en/packet-EOF_Packet.html (which is linked from the docs you are referring to).

I'm not finding the *found rows* nor the *affected rows* on the `EOF_Packet` documentation though. What I'm finding in several documentations such as [Understading MySQL Internals](http://www.oreilly.de/catalog/9780596009571/chapter/ch04.pdf) is:

> Normally, in reporting the results of an UPDATE query, the
> server returns the number of records that were actually modified.
> If this flag is set, the server is being asked to report the
> number of records that were matched by the WHERE clause.
> Not all of those will necessarily be updated, as some may
> already contain the desired values.

I guess we could have a conditional on that on the qmynd driver and then expose it to pgloader so that we can connect without requiring that capability. Again sounds really strange to me to have a server with no support for what I understand is such a basic capability.

**Comment by pinaraf** [comment]
> I guess we could have a conditional on that on the qmynd driver and then expose it to pgloader so that we can connect without requiring that capability. Again sounds really strange to me to have a server with no support for what I understand is such a basic capability.


I agree that it sounds strange, but this capability was likely introduced in MySQL 5.1 (I still have to live with MySQL 5.0 at work, and I found no MySQL 5.0 supporting it).
But it's not that basic, it's only about UPDATE queries reporting the number of found rows instead of the number of affected rows. It seems quite specific to me.

**Comment by dimitri** [comment]
In those lights I made the driver default to not using client_found_rows, I hope it's correct to do so, it's what I've seen done in several other driver implementations (go, javascript and other CL ones). You should be able to benefit from the change by doing:

    rm -rf ./build/quicklisp/local-projects/qmynd
    make

Or alternatively go `git pull` in the qmynd subdirectory.

**Comment by pinaraf** [comment]
Thank you a lot, I'll test that in the next days, it will great to be able to use pgloader !
