### ISSUE TITLE
Control stack guard page temporarily disabled:

### ISSUE THREAD

**Issue by adhi1226** [dimitri/pgloader#974]
```
pc@LENOVO:~/pgloader$ pgloader mysql://root:xxxx@localhost/db postgresql://pc:xxxx@127.0.0.1/db
2019-05-21T09:49:52.050000Z LOG Migrating from #<MYSQL-CONNECTION mysql://root@localhost:3306/db{1005C19F03}>
2019-05-21T09:49:52.053000Z LOG Migrating into #<PGSQL-CONNECTION pgsql://pc@127.0.0.1:5432/db {1005E54D93}>
KABOOM!
INFO: Control stack guard page unprotected
Control stack guard page temporarily disabled: proceed with caution

What I am doing here?

Control stack exhausted (no more space for function call frames).
This is probably due to heavily nested or infinitely recursive function
calls, or a tail call that SBCL cannot or has not optimized away.

PROCEED WITH CAUTION.
```

**Comment by dimitri** [comment]
This looks like a bug that has been fixed already. Please update your pgloader copy, either compile it from source here (`make save` should just work) or use the docker image that are built at each commit.

If you're using the current version of pgloader (from sources) and still have that issue, please re-open and provide a full `--debug` output.

**Comment by adhi1226** [comment]
Thank you..will try and update asap.

**Comment by sahilabro** [comment]
Hi,

It doesn't work for me either. I am migrating a MariaDB to postgres. It works with postgres 12 but not postgres 11. It consistently gives me the aforementioned control stack error. I have tried different variations of prefetch rows, batch size, workers & concurrency. Still gives me the same error.

`2020-08-06T10:30:13.009000+01:00 LOG pgloader version "3.6.2"
2020-08-06T10:30:13.011000+01:00 LOG Data errors in '/private/tmp/pgloader/'
2020-08-06T10:30:13.011000+01:00 LOG Parsing commands from file #P"/Users/sao13/src/scripts/pgloader"
2020-08-06T10:30:13.783000+01:00 LOG Migrating from #<MYSQL-CONNECTION mysql://x
2020-08-06T10:30:13.783000+01:00 LOG Migrating into #<PGSQL-CONNECTION pgsql://x
KABOOM!
INFO: Control stack guard page unprotected
Control stack guard page temporarily disabled: proceed with caution

What I am doing here?

Control stack exhausted (no more space for function call frames).
This is probably due to heavily nested or infinitely recursive function
calls, or a tail call that SBCL cannot or has not optimized away.

PROCEED WITH CAUTION.`


I am using pgloader version 3.6.2 

Would appreciate any help :)
